### ISSUE TITLE
name 'g_kg' is not defined

### ISSUE THREAD

**Issue by 4grass** [johnnyjana730/MVIN#2]
When I compile your code, it emerges an error, which shows that name 'g_kg' is not defined happening in data_loader_user_set.py.  Thank you for your time over my issue.

**Comment by johnnyjana730** [comment]
the code should set the g_kg as global variable. 

anyway you can try to disable parallel processing, such as
![image](https://user-images.githubusercontent.com/20666568/120922698-3c8f9380-c6fd-11eb-8381-984500c9d552.png)
